Update menu

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -137,30 +137,30 @@ read -n 1 -s -r -p "Press any key to return to the menu"
             clear
             # Display menu
             display_menu() {
-echo -e "${dark_blue_bg}${orange}              ☯ MERAUKE PROJECT TUNNELING ☯              ${neutral}"
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mOS            \e[38;5;87m:  "`hostnamectl | grep "Operating System" | cut -d ' ' -f5-`
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mIP            \e[38;5;87m:  $(curl -s ipv4.icanhazip.com 2>/dev/null || echo "Unable to detect IP")"
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mRAM           \e[38;5;87m:  $(free -m | awk 'NR==2 {print $3 "MB / " $2 "MB"}')"
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mISP           \e[38;5;87m:  $(curl -s ipinfo.io/org 2>/dev/null | cut -d ' ' -f 2-100 || echo "Unable to detect ISP")"
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mCITY          \e[38;5;87m:  $(curl -s ipinfo.io/city 2>/dev/null || echo "Unable to detect city")"
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mDOMAIN        \e[38;5;87m:  $(head -n1 /etc/xray/domain 2>/dev/null || echo "No domain registered")"
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mDATE & TIME   \e[38;5;87m:  $(date -R | cut -d " " -f -5)"
-echo -e "${orange} \e[38;5;196m• \e[38;5;226mUPTIME        \e[38;5;87m:  $(uptime -p 2>/dev/null | cut -d ' ' -f 2-10000 || echo "Unable to detect uptime")"
-echo -e "${dark_blue_bg}${orange}                 ☯ STATUS SERVICE ☯                 ${neutral}"
+echo -e "${dark_blue_bg}${pink}              ☯ MERAUKE PROJECT TUNNELING ☯              ${neutral}"
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mOS            \e[38;5;87m:  \e[38;5;141m"`hostnamectl | grep "Operating System" | cut -d ' ' -f5-`
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mIP            \e[38;5;87m:  \e[38;5;141m$(curl -s ipv4.icanhazip.com 2>/dev/null || echo "Unable to detect IP")"
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mRAM           \e[38;5;87m:  \e[38;5;141m$(free -m | awk 'NR==2 {print $3 "MB / " $2 "MB"}')"
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mISP           \e[38;5;87m:  \e[38;5;141m$(curl -s ipinfo.io/org 2>/dev/null | cut -d ' ' -f 2-100 || echo "Unable to detect ISP")"
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mCITY          \e[38;5;87m:  \e[38;5;141m$(curl -s ipinfo.io/city 2>/dev/null || echo "Unable to detect city")"
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mDOMAIN        \e[38;5;87m:  \e[38;5;141m$(head -n1 /etc/xray/domain 2>/dev/null || echo "No domain registered")"
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mDATE & TIME   \e[38;5;87m:  \e[38;5;141m$(date -R | cut -d " " -f -5)"
+echo -e "${orange} \e[38;5;196m• \e[38;5;226mUPTIME        \e[38;5;87m:  \e[38;5;141m$(uptime -p 2>/dev/null | cut -d ' ' -f 2-10000 || echo "Unable to detect uptime")"
+echo -e "${dark_blue_bg}${pink}                   ☯ STATUS SERVICE ☯                    ${neutral}"
 echo -e "    ${yellow}XRAY \e[38;5;87m: "$(cek_status vmess@config)"${yellow}   HAPROXY \e[38;5;87m: "$(cek_status haproxy)"${yellow}  SSHOVPN \e[38;5;87m: "$(cek_status ssh)" ${neutral}"
-printf "\e[0m%-13s %-7s %-8s %2s\n" "            SSH       VMESS         VLESS        TROJAN        SSWS        ACCOUNT "
-printf "\e[0m%-13s %-7s %-8s %2s\n" "            $ssh         $vm             $vl             $tr             $ss             PREMIUM "
-echo -e "${dark_blue_bg}${orange}                 ☯ MENU AUTOSCRIPT ☯                 ${neutral}"
+printf "\e[0m%-13s %-7s %-8s %2s\n" "${dark_gray}[ACCOUNT]\e[38;5;87m  :  \e[38;5;141mSSH      VMESS       VLESS      TROJAN       SSWS        ${neutral} "
+printf "\e[0m%-13s %-7s %-8s %2s\n" "${light_gray}[PREMIUM]\e[38;5;87m  :  \e[38;5;141m$ssh        $vm           $vl           $tr            $ss         ${neutral}  "
+echo -e "${dark_blue_bg}${pink}                   ☯ MENU AUTOSCRIPT ☯                   ${neutral}"
 echo -e " ${orange}[$green 01 ${orange}] \e[38;5;226mSsh Menu        ${orange}[$green 05 ${orange}] \e[38;5;226mShdwscks Menu    ${neutral}"
 echo -e " ${orange}[$green 02 ${orange}] \e[38;5;226mVmess Menu      ${orange}[$green 06 ${orange}] \e[38;5;226mNotif Bot Menu   ${neutral}"
 echo -e " ${orange}[$green 03 ${orange}] \e[38;5;226mVless Menu      ${orange}[$green 07 ${orange}] \e[38;5;226mBot Telegram Menu${neutral}"
 echo -e " ${orange}[$green 04 ${orange}] \e[38;5;226mTrojan Menu     ${orange}[$green 08 ${orange}] \e[38;5;226mSettings Menu    ${neutral}"
-echo -e "${dark_blue_bg}             ${green}SCRIPT VERSION: V10.0 LTS${neutral}"
+echo -e "${dark_blue_bg}                 ${pink}SCRIPT VERSION: V10.0 LTS                ${neutral}"
 echo -e "                ${orange}───${green}───${yellow}───${blue}───${purple}───${red}───${neutral}"
 echo -e " [\e[36m•x\e[0m] Exit Panel"
-echo -e "${dark_blue_bg}${orange}              ☯ OTHER DETAILS ☯               ${neutral}"
-echo -e "   ${red} • ${neutral}ID CLIENTS : ${neutral}$username ${sts}"            
-echo -e "   ${red} • ${neutral}SC EXPIRED : ${neutral}$(datediff "$Exp1" "$today")"
+echo -e "${dark_blue_bg}${pink}                    ☯ OTHER DETAILS ☯                    ${neutral}"
+echo -e "   ${red} • ${yellow}ID CLIENTS \e[38;5;87m:  \e[38;5;141m$username ${sts}"            
+echo -e "   ${red} • ${yellow}SC EXPIRED \e[38;5;87m:  \e[38;5;141m$(datediff "$Exp1" "$today")"
 echo -e " "
 read -p "Pick a number (1-8) or hit 'x' to bail: " choice
     echo -e ""
